#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$configuration = new Radweb\EC2SSH\Configuration($_SERVER['HOME'] . '/.ec2ssh');

$application = new Symfony\Component\Console\Application();

$application->addCommands([
  new Radweb\EC2SSH\RunCommand($configuration),
  new Radweb\EC2SSH\ConfigureCommand($configuration),
]);

$application->setDefaultCommand('run');

$application->run();
